baseurl: "http://labs.neueda.com"
title: "Neueda R&D"
languageCode: "en-us"
metaDataFormat: "yaml"
canonifyurls: true
publishdir: "build"

permalinks:
  post: /:year/:month/:day/:title/

menu:
  main:
    - name: "Join Us"
      identifier: "join-us"
      weight: 0
      url: "/"
